services:
  db:
    image: postgres:15
    container_name: historical_db
    environment:
      POSTGRES_DB: app_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data